### ISSUE TITLE
Support for email : @qq.com

### ISSUE THREAD

**Issue by JessBobby** [noodle-run/noodle#369]
In China,myaccount@qq.com is not allowed to access this application.
@qq.com is the email supported by Tencent.
Hope support it.

**Comment by Erb3** [comment]
Hello,

The error you are seeing ("You are not allowed to access this application."), is unrelated to your email domain. I believe the error comes because Noodle is not in a usable state, and for that reason does not allow users to create accounts. However you are free to request early access and get notified once Noodle is ready: [noodle.run/early-access](https://noodle.run/early-access).

**Comment by JessBobby** [comment]
Thank you!
